### ISSUE TITLE
Plugin breaks routing to the root path (/)

### ISSUE THREAD

**Issue by jwoudenberg** [router5/router5-persistent-params#1]
I noticed in a project that when enabling this plugin, loading my site at the root path (e.g.: example.com) would result in a 'ROUTE NOT FOUND'. I managed to reproduce the error in the code sample below:

```js
const { Router5 } = require('router5');
const persistentParamsPlugin = require('router5-persistent-params').default;
const router = new Router5()
  .usePlugin(persistentParamsPlugin(['foo']))
  .setOption('trailingSlash', true)
  .addNode('home', '/')
  .addNode('persons', '/persons')
  .start();
console.log(router.matchPath('/persons')); // -> ✓
console.log(router.matchPath('/'));        // -> null
console.log(router.matchPath(''));         // -> null
```

Taking out the `usePlugin` line in the code sample below, and all paths are matched.

I'm using the latest versions of both router5 (3.0.3) and persistent-params (3.0.0).

**Comment by troch** [comment]
Looks like a bug. I'll fix it in the coming weeks. If you set `trailingSlash` to `false` does `router.matchPath('/')` work?

**Comment by jwoudenberg** [comment]
Thanks for the quick response! Just checked: `router.matchPath('/')` does with if `trailingSlash` is set to `false.

**Comment by troch** [comment]
Issue waswith route-node package which has now been fixed (see linked commit). `1.4.4` of route-node has been released, I'm not linking it yet to router5 but if you do re-install router5 you'll get the patch.

**Comment by jwoudenberg** [comment]
It works perfectly. Thanks for the effort, it's appreciated :).
